# Change these first
owner: chillwave # Your GitHub organization or username, where this repository lives
repo: uptime.valdi-via # The name of this repository

sites:
  - name: Dump1090 SFL
    url: http://119xx.valdi-via.com:11090
  - name: AT&T - Outage Map
    url: https://www.att.com/outages
  - name: Florida Power & Light - Outage Map
    url: https://www.fplmaps.com/
  - name: Duke Energy (FL)- Outage Map
    url: https://outagemaps.duke-energy.com/#/current-outages/fl
  - name: Xfinity - Outage Map
    url: https://www.xfinity.com/support/statusmap
  - name: Verizon - Status Center
    url: https://verizon.com/CheckStatus
  - name: Comcast Buisness - Status Center
    url: https://www.xfinity.com/support/statusmap
  - name: Lumen - Account Portal
    url: https://www.lumen.com/login
  - name: CenturyLink - Account Portal
    url: https://dh.centurylink.com/    
    
status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: statmon.valdi-via.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Valdi-via networks status monitor, powered by [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Actions token expires on May 1, 2025 - service is reliant on this.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
